### PR TITLE
fix: frame length can not be 0

### LINKED ISSUE #129: FrameLength can not be zero, and must be less than Maximum. FRAME_SIZE
Both of these need to be preconditions in `serialize` at a minimum

### PR DESCRIPTION
**Pull request by seebees**
resolves #129

The other ESDK’s use frameLength === 0 to indicate non-framed content.
The JS ESDK does not support encrypting non-framed content.
A frameLength of 0 will crash the process.
Add condition and test.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: modules/encrypt-browser/src/encrypt.ts [hunk 1]
```diff
@@ -60,6 +62,10 @@ export async function encrypt (
   plaintext: Uint8Array,
   { suiteId, encryptionContext, frameLength = FRAME_LENGTH }: EncryptInput = {}
 ): Promise<EncryptResult> {
+
+  /* Precondition: The frameLength must be less than the maximum frame size for browser encryption. */
+  needs(frameLength > 0 && Maximum.FRAME_SIZE >= frameLength, 'frameLength out of bounds')
```
Comment (mattsb42-aws) [inline modules/encrypt-browser/src/encrypt.ts]: Can we add those bounds to the error message?

Comment (seebees) [reply modules/encrypt-browser/src/encrypt.ts]: fixed, in both... :)
